FROM ubuntu
ENV API_URL="http://localhost:8000"

RUN apt-get update && apt-get install -yf curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get install -yf git curl gnupg2 nodejs && \
    git clone https://github.com/docker-hy/frontend-example-docker.git && \
    node -v && npm -v && cd frontend-example-docker && npm install && \
    apt-get purge -y --auto-remove curl git && \ 
    rm -rf /var/lib/apt/lists/* 

EXPOSE 5000 

WORKDIR frontend-example-docker
ENTRYPOINT ["/usr/bin/npm", "start"]
