FROM alpine as build-env

RUN apk add --update --no-cache curl git curl gnupg nodejs nodejs-npm && \
    git clone https://github.com/docker-hy/frontend-example-docker.git /frontend && \
    node -v && npm -v && cd frontend && npm install && \
    apk del curl git 



FROM node:alpine

ENV API_URL="http://localhost:8000"

WORKDIR /home/node/frontend
COPY --from=build-env /frontend ./
EXPOSE 5000
ENTRYPOINT ["/usr/bin/npm", "start"]
