FROM node AS build-env
ENV API_URL="http://localhost:8000"

RUN git clone https://github.com/docker-hy/frontend-example-docker.git /frontend && \
    cd /frontend && npm install

FROM node:alpine
ENV API_URL="http://localhost:8000"
EXPOSE 5000 
WORKDIR /home/node/frontend

COPY --from=build-env /frontend ./

ENTRYPOINT ["/usr/bin/npm", "start"]
