FROM ubuntu 
RUN apt-get update && apt-get install -yf python3 python3-pip ffmpeg curl && useradd -m app 
USER app
RUN pip3 install --user --upgrade yle-dl youtube-dl
WORKDIR /app
ENTRYPOINT ["/home/app/.local/bin/yle-dl"]

