FROM node AS build-env
ENV PORT=8000
ENV FRONT_URL="http://localhost:5000"
RUN git clone https://github.com/docker-hy/backend-example-docker.git /backend && \
    cd /backend && npm install


FROM node:alpine

ENV PORT=8000
ENV FRONT_URL="http://localhost:5000"

WORKDIR /home/node/backend
COPY --from=build-env /backend ./
EXPOSE 8000
ENTRYPOINT ["/usr/bin/npm", "start"]
