FROM alpine AS build-env

RUN apk add --update --no-cache curl git curl gnupg nodejs nodejs-npm && \
    git clone https://github.com/docker-hy/backend-example-docker.git /backend && \
    node -v && npm -v && cd backend && npm install

FROM node:alpine

ENV PORT=8000
ENV FRONT_URL="http://localhost:5000"

USER node
WORKDIR /home/node/backend
COPY --from=build-env /backend ./
EXPOSE 8000
ENTRYPOINT ["/usr/bin/npm", "start"]
